FROM ghcr.io/tcapelle/pt21_base:v0

WORKDIR /workspace

RUN git clone --depth=1 https://github.com/huggingface/alignment-handbook.git

WORKDIR /workspace/alignment-handbook

COPY requirements.txt /workspace/alignment-handbook
RUN python -m pip install -r requirements.txt